#! /bin/sh
bspc rule -r "*"

bspc monitor DP-0 -d 1 2 3 4 5 6

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a brave-browser desktop='^2'
bspc rule -a spotify desktop='^6'

# Auto start
sh $HOME/.config/bspwm/apps-start.sh

#BSPWM configuration
bspc config border_width         2
bspc config window_gap           10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
